baseURL = "http://www.flysnow.org"
languageCode = "zh-CN"
title = "Happy JiaHui"
theme = "maupassant"

[author]
  name = "zhaojinbing"

[params]
  author = "zhaojinbing"
  subtitle = "快乐人生 分享技术"
  keywords = "java"
  description = "专注于Java、项目管理、软件架构"
